networks:
  app_network:
    driver: bridge

services:
  app:
    build: .
    container_name: ${PROJECT_NAME}-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - SECRET_KEY=${SECRET_KEY}
      - PROJECT_NAME=${PROJECT_NAME}

    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app_network
    command: >
      sh -c "alembic upgrade head && fastapi dev app/main.py --host 0.0.0.0 --port 8000"

  db:
    image: postgres:17
    container_name: ${PROJECT_NAME}-db
    ports:
      - "${LOCAL_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:
